"""
Lineage: per-tendency record of engine activity.

Events are not generated by an external clock. They *are* the engine's
activity: stakes placed, allocations shifted, tendencies born or
culled, claims mutated. The engine's tick is its own breath.

Each event has an originating tendency and an engine-time stamp from a
global monotonic counter. Engine-time is global (one clock for the
whole system) but does not map onto wall-clock or 4th-dimension time;
it only ticks when the engine acts.

Producer-consumer split
=======================

Emission is cheap: the recorder appends the event to the originating
tendency's outbox and advances the clock. Nothing else happens. There
is no propagation at emit-time.

Consumption is on-demand. When a caller needs to know "what activity
is visible to tendency X?", it calls ``Lineage.pull_view(...)`` (or
the recorder convenience), which walks the stake-weight graph from
X out to a configurable radius and threshold, gathering events from
reachable neighbors' outboxes. Pulls are read-only: they advance no
clock, modify no state, leave no record. The cost of inference is
controlled at query time, per query.

Retention policy
================

Outbox storage is configurable via a strategy:

  - ``UnboundedPolicy`` -- outbox grows; deployer commits to storage.
  - ``DropOldestPolicy`` -- bounded ring; oldest evicted on overflow.
  - ``RefuseWhenFullPolicy`` -- bounded ring; raises on overflow.
  - ``BoundedRingPlusCompactionPolicy`` -- bounded tier-0 ring; on
    overflow, evicted events are demoted via the LOD protocol's
    reduce step and spilled into a tier-1 ring; tier-1 overflow does
    the same; etc. Each tier's capacity and target LOD are
    configurable. The framework provides the policy; the deployer
    picks tier counts and budgets.

Visibility scales with sparsity
================================

A tendency's visible activity is its own outbox plus any neighbor
outboxes its pull reaches. Distant tendencies (weights trending to
zero) are simply not visible to local pulls. The graph topology is
the visibility rule.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Iterable, Optional, Protocol


# ---------------------------------------------------------------------------
# Event types
# ---------------------------------------------------------------------------


class EventType(Enum):
    """The kinds of activity the engine emits."""

    STAKED              = "staked"
    ALLOCATION_SHIFTED  = "allocation_shifted"
    BORN                = "born"
    CULLED              = "culled"
    CLAIM_MUTATED       = "claim_mutated"


@dataclass(frozen=True)
class Event:
    """A single unit of engine activity.

    ``lod`` records what level of detail this event currently carries.
    Newly emitted events are always at the protocol's max level
    (full fidelity); compaction policies may demote them.
    """

    engine_time: int
    type: EventType
    origin_id: str
    payload: dict = field(default_factory=dict)
    wall_clock: Optional[float] = None
    lod: int = 3   # default: assume LOD 3 (full); compaction may demote

    def to_dict(self) -> dict:
        return {
            "engine_time": self.engine_time,
            "type": self.type.value,
            "origin_id": self.origin_id,
            "payload": dict(self.payload),
            "wall_clock": self.wall_clock,
            "lod": self.lod,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Event":
        return cls(
            engine_time=int(data["engine_time"]),
            type=EventType(data["type"]),
            origin_id=str(data["origin_id"]),
            payload=dict(data.get("payload", {})),
            wall_clock=data.get("wall_clock"),
            lod=int(data.get("lod", 3)),
        )


# ---------------------------------------------------------------------------
# Engine clock
# ---------------------------------------------------------------------------


@dataclass
class EngineClock:
    """Monotonic counter advanced once per event emission."""

    value: int = 0

    def tick(self) -> int:
        self.value += 1
        return self.value

    def now(self) -> int:
        return self.value


# ---------------------------------------------------------------------------
# Retention policies (storage strategies)
# ---------------------------------------------------------------------------


class RetentionPolicy(Protocol):
    """Strategy for outbox storage. The deployer picks one per Lineage."""

    def record(self, event: Event) -> None:
        """Store an event. May raise if full and policy refuses."""

    def events(self) -> list[Event]:
        """Return all currently-retained events in arrival order."""

    def __len__(self) -> int: ...

    def to_dict(self) -> dict: ...


@dataclass
class UnboundedPolicy:
    """Outbox grows without limit. Deployer commits to having enough memory."""

    storage: list[Event] = field(default_factory=list)

    def record(self, event: Event) -> None:
        self.storage.append(event)

    def events(self) -> list[Event]:
        return list(self.storage)

    def __len__(self) -> int:
        return len(self.storage)

    def to_dict(self) -> dict:
        return {
            "kind": "unbounded",
            "events": [e.to_dict() for e in self.storage],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "UnboundedPolicy":
        return cls(storage=[Event.from_dict(e) for e in data.get("events", [])])


@dataclass
class DropOldestPolicy:
    """Bounded ring; oldest evicted on overflow. Lossy by design, predictable."""

    capacity: int = 256
    storage: deque[Event] = field(default_factory=deque)

    def __post_init__(self) -> None:
        if self.storage.maxlen != self.capacity:
            self.storage = deque(self.storage, maxlen=self.capacity)

    def record(self, event: Event) -> None:
        self.storage.append(event)

    def events(self) -> list[Event]:
        return list(self.storage)

    def __len__(self) -> int:
        return len(self.storage)

    def to_dict(self) -> dict:
        return {
            "kind": "drop_oldest",
            "capacity": self.capacity,
            "events": [e.to_dict() for e in self.storage],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "DropOldestPolicy":
        p = cls(capacity=int(data.get("capacity", 256)))
        for e in data.get("events", []):
            p.record(Event.from_dict(e))
        return p


@dataclass
class RefuseWhenFullPolicy:
    """Bounded ring; raises ``OutboxFullError`` on overflow."""

    capacity: int = 256
    storage: list[Event] = field(default_factory=list)

    def record(self, event: Event) -> None:
        if len(self.storage) >= self.capacity:
            raise OutboxFullError(
                f"outbox full at capacity {self.capacity}; refusing to record event "
                f"engine_time={event.engine_time}"
            )
        self.storage.append(event)

    def events(self) -> list[Event]:
        return list(self.storage)

    def __len__(self) -> int:
        return len(self.storage)

    def to_dict(self) -> dict:
        return {
            "kind": "refuse_when_full",
            "capacity": self.capacity,
            "events": [e.to_dict() for e in self.storage],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "RefuseWhenFullPolicy":
        p = cls(capacity=int(data.get("capacity", 256)))
        for e in data.get("events", []):
            p.record(Event.from_dict(e))
        return p


class OutboxFullError(RuntimeError):
    """Raised by ``RefuseWhenFullPolicy`` when an emit would overflow."""


@dataclass
class CompactionTier:
    """One rung of a compaction pyramid.

    Parameters
    ----------
    capacity:
        Number of events this tier holds.
    target_lod:
        LOD level events are demoted to when they enter this tier.
        Lower than the tier above (or unchanged for tier 0).
    """

    capacity: int
    target_lod: int


@dataclass
class BoundedRingPlusCompactionPolicy:
    """Tiered outbox: full-fidelity recent ring, compressed deeper tiers.

    Tier 0 holds the most recent events at full LOD. Overflow from
    tier 0 is demoted (via ``demote_fn``) to ``tiers[1].target_lod``
    and pushed into tier 1. Overflow from tier 1 goes to tier 2 at
    its lower LOD. Etc. Overflow from the deepest tier is dropped.

    The framework provides the storage; the deployer provides the
    tier list and the demotion function (which typically wraps
    ``protocol.reduce`` from the LOD module).
    """

    tiers: list[CompactionTier] = field(default_factory=list)
    storage: list[deque[Event]] = field(default_factory=list, repr=False)
    demote_fn: Optional[object] = field(default=None, repr=False)
    # demote_fn signature: (event: Event, target_lod: int) -> Event

    def __post_init__(self) -> None:
        if not self.tiers:
            # Sensible default: 3-tier pyramid 256 / 1024 / 4096 at LODs 3 / 2 / 1.
            self.tiers = [
                CompactionTier(capacity=256,  target_lod=3),
                CompactionTier(capacity=1024, target_lod=2),
                CompactionTier(capacity=4096, target_lod=1),
            ]
        if not self.storage or len(self.storage) != len(self.tiers):
            self.storage = [deque(maxlen=t.capacity) for t in self.tiers]

    def record(self, event: Event) -> None:
        # Newly emitted events always enter tier 0 at the event's own LOD.
        self._spill(0, event)

    def _spill(self, tier_index: int, event: Event) -> None:
        if tier_index >= len(self.tiers):
            return  # off the end -- dropped
        tier = self.tiers[tier_index]
        ring = self.storage[tier_index]

        # Demote to this tier's target LOD if needed
        target_lod = tier.target_lod
        if event.lod != target_lod and self.demote_fn is not None:
            event = self.demote_fn(event, target_lod)

        # If full, evict oldest and recurse-spill into next tier
        if len(ring) == tier.capacity:
            evicted = ring.popleft()
            self._spill(tier_index + 1, evicted)

        ring.append(event)

    def events(self) -> list[Event]:
        out: list[Event] = []
        # Order: oldest-deepest-tier first, newest-tier-0 last.
        for ring in reversed(self.storage):
            out.extend(ring)
        # Within tier order, sort by engine_time so the global ordering
        # is consistent across mixed tiers.
        out.sort(key=lambda e: e.engine_time)
        return out

    def __len__(self) -> int:
        return sum(len(r) for r in self.storage)

    def to_dict(self) -> dict:
        return {
            "kind": "bounded_ring_plus_compaction",
            "tiers": [{"capacity": t.capacity, "target_lod": t.target_lod}
                      for t in self.tiers],
            "storage": [[e.to_dict() for e in ring] for ring in self.storage],
        }

    @classmethod
    def from_dict(cls, data: dict, demote_fn: Optional[object] = None) -> "BoundedRingPlusCompactionPolicy":
        tiers = [CompactionTier(capacity=int(t["capacity"]),
                                target_lod=int(t["target_lod"]))
                 for t in data.get("tiers", [])]
        p = cls(tiers=tiers, demote_fn=demote_fn)
        # Reload storage explicitly without re-running compaction logic
        for tier_index, ring_data in enumerate(data.get("storage", [])):
            if tier_index >= len(p.storage):
                continue
            for ev in ring_data:
                p.storage[tier_index].append(Event.from_dict(ev))
        return p


def policy_from_dict(data: dict, demote_fn: Optional[object] = None) -> RetentionPolicy:
    """Reconstruct any RetentionPolicy from its serialized form."""
    kind = data.get("kind", "drop_oldest")
    if kind == "unbounded":
        return UnboundedPolicy.from_dict(data)
    if kind == "drop_oldest":
        return DropOldestPolicy.from_dict(data)
    if kind == "refuse_when_full":
        return RefuseWhenFullPolicy.from_dict(data)
    if kind == "bounded_ring_plus_compaction":
        return BoundedRingPlusCompactionPolicy.from_dict(data, demote_fn=demote_fn)
    raise ValueError(f"unknown retention policy kind: {kind!r}")


# ---------------------------------------------------------------------------
# Per-tendency lineage storage
# ---------------------------------------------------------------------------


@dataclass
class Lineage:
    """Per-tendency lineage: rolling allocation window + outbox.

    The outbox stores events the tendency *itself* emitted. Events from
    other tendencies are not propagated here at emit-time; callers
    that need a broader view use ``pull_view``.

    Rolling allocation window is separate from the outbox. It tracks
    the tendency's own allocation values across recent shifts, fixed
    capacity, drop-oldest. This is LOD 1 fodder.

    Default policy is ``DropOldestPolicy(capacity=256)``. Deployers
    pick a different policy by passing it to the constructor.
    """

    allocation_window_capacity: int = 32
    allocation_window: deque[float] = field(default_factory=lambda: deque(maxlen=32))
    outbox: RetentionPolicy = field(default_factory=lambda: DropOldestPolicy())

    def __post_init__(self) -> None:
        if self.allocation_window.maxlen != self.allocation_window_capacity:
            self.allocation_window = deque(
                self.allocation_window, maxlen=self.allocation_window_capacity
            )

    # ------------------------------------------------------------------
    # Append (used by the recorder; tests may also call directly)
    # ------------------------------------------------------------------

    def record_event(self, event: Event) -> None:
        """Append an event to the outbox per the retention policy."""
        self.outbox.record(event)

    def record_allocation(self, allocation: float) -> None:
        """Append a post-shift allocation to the rolling window."""
        self.allocation_window.append(allocation)

    # ------------------------------------------------------------------
    # Query (own outbox only)
    # ------------------------------------------------------------------

    def recent_allocations(self) -> list[float]:
        return list(self.allocation_window)

    def events(self) -> list[Event]:
        """Events this tendency itself emitted, in arrival order."""
        return self.outbox.events()

    def latest_event(self) -> Optional[Event]:
        evs = self.outbox.events()
        return evs[-1] if evs else None

    def events_of_type(self, type: EventType) -> list[Event]:
        return [e for e in self.outbox.events() if e.type == type]

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    def to_dict(self) -> dict:
        return {
            "allocation_window_capacity": self.allocation_window_capacity,
            "allocation_window": list(self.allocation_window),
            "outbox": self.outbox.to_dict(),
        }

    @classmethod
    def from_dict(cls, data: dict, demote_fn: Optional[object] = None) -> "Lineage":
        outbox_data = data.get("outbox")
        if outbox_data is not None:
            outbox = policy_from_dict(outbox_data, demote_fn=demote_fn)
        else:
            # Legacy v1 shape: top-level event_ring + capacity
            outbox = DropOldestPolicy(
                capacity=int(data.get("event_ring_capacity", 256))
            )
            for ev in data.get("event_ring", []):
                outbox.record(Event.from_dict(ev))

        ln = cls(
            allocation_window_capacity=int(data.get("allocation_window_capacity", 32)),
            outbox=outbox,
        )
        for v in data.get("allocation_window", []):
            ln.record_allocation(float(v))
        return ln


# ---------------------------------------------------------------------------
# Stake-weight graph view (read-only structural input for pulls)
# ---------------------------------------------------------------------------


@dataclass
class StakeWeightGraph:
    """Symmetric stake-weight graph between tendencies.

    The arena keeps this current. Pulls consult it to determine
    visibility neighborhoods.
    """

    weights: dict[str, dict[str, float]] = field(default_factory=dict)

    def neighbors(self, tid: str, min_weight: float) -> list[tuple[str, float]]:
        adj = self.weights.get(tid, {})
        out = [(o, w) for o, w in adj.items() if o != tid and w >= min_weight]
        out.sort(key=lambda pair: -pair[1])
        return out

    def has(self, tid: str) -> bool:
        return tid in self.weights

    def add_edge(self, a: str, b: str, weight: float) -> None:
        if a == b:
            return
        self.weights.setdefault(a, {})[b] = weight
        self.weights.setdefault(b, {})[a] = weight

    def add_tendency(self, tid: str) -> None:
        self.weights.setdefault(tid, {})

    def remove_tendency(self, tid: str) -> None:
        for other in list(self.weights.get(tid, {})):
            self.weights[other].pop(tid, None)
        self.weights.pop(tid, None)

    def edge_weight(self, a: str, b: str) -> float:
        return self.weights.get(a, {}).get(b, 0.0)


# ---------------------------------------------------------------------------
# Lineage recorder
# ---------------------------------------------------------------------------


@dataclass
class LineageRecorder:
    """Writes events to outboxes; provides pulls as a separate operation.

    Emission is cheap: ``emit()`` advances the clock and appends one
    event to the originating tendency's outbox. No graph walk, no
    propagation, no side effects on other tendencies.

    Pulls (``pull_view``) walk the stake-weight graph from a focal
    tendency, gathering events from reachable neighbors' outboxes.
    Pulls are read-only. They take radius and threshold as parameters
    so the caller controls the cost/accuracy tradeoff per query.
    """

    clock: EngineClock
    graph: StakeWeightGraph
    lineages: dict[str, Lineage] = field(default_factory=dict)

    # Default pull parameters; callers may override per pull.
    default_pull_min_weight: float = 0.01
    default_pull_radius: int = 2

    # ------------------------------------------------------------------
    # Setup helpers
    # ------------------------------------------------------------------

    def register(self, tendency_id: str, lineage: Optional[Lineage] = None) -> Lineage:
        """Add a lineage slot for a tendency. Idempotent."""
        if tendency_id in self.lineages:
            return self.lineages[tendency_id]
        ln = lineage or Lineage()
        self.lineages[tendency_id] = ln
        self.graph.add_tendency(tendency_id)
        return ln

    def unregister(self, tendency_id: str) -> Optional[Lineage]:
        """Remove a tendency's lineage slot; also drops graph edges."""
        self.graph.remove_tendency(tendency_id)
        return self.lineages.pop(tendency_id, None)

    # ------------------------------------------------------------------
    # Emission (origin-only)
    # ------------------------------------------------------------------

    def emit(
        self,
        type: EventType,
        origin_id: str,
        payload: Optional[dict] = None,
        wall_clock: Optional[float] = None,
        lod: int = 3,
    ) -> Event:
        """Build an event and record it on the origin's outbox only.

        No propagation. Other tendencies will see this event via pulls.
        """
        event = Event(
            engine_time=self.clock.tick(),
            type=type,
            origin_id=origin_id,
            payload=dict(payload or {}),
            wall_clock=wall_clock,
            lod=lod,
        )
        ln = self.lineages.get(origin_id)
        if ln is not None:
            ln.record_event(event)
        return event

    def emit_allocation_shift(
        self,
        origin_id: str,
        new_allocation: float,
        delta: float,
        wall_clock: Optional[float] = None,
    ) -> Event:
        """Emit ALLOCATION_SHIFTED and update origin's allocation window."""
        event = self.emit(
            type=EventType.ALLOCATION_SHIFTED,
            origin_id=origin_id,
            payload={"new_allocation": new_allocation, "delta": delta},
            wall_clock=wall_clock,
        )
        ln = self.lineages.get(origin_id)
        if ln is not None:
            ln.record_allocation(new_allocation)
        return event

    # ------------------------------------------------------------------
    # Pulls (read-only consumption)
    # ------------------------------------------------------------------

    def pull_view(
        self,
        focal_id: str,
        radius: Optional[int] = None,
        min_weight: Optional[float] = None,
    ) -> list[Event]:
        """Return events visible to ``focal_id`` under the given pull parameters.

        Walks the stake-weight graph from ``focal_id`` out to ``radius``
        hops along edges of weight >= ``min_weight``, collecting events
        from each reached tendency's outbox. The focal tendency's own
        events are always included.

        Returns events sorted by engine_time. Read-only -- no side
        effects on outboxes, the graph, or the clock.
        """
        radius = self.default_pull_radius if radius is None else radius
        min_weight = (
            self.default_pull_min_weight if min_weight is None else min_weight
        )
        reachable = self._reachable(focal_id, radius, min_weight)
        events: list[Event] = []
        for tid in reachable:
            ln = self.lineages.get(tid)
            if ln is not None:
                events.extend(ln.events())
        events.sort(key=lambda e: e.engine_time)
        return events

    def reachable_set(
        self,
        focal_id: str,
        radius: Optional[int] = None,
        min_weight: Optional[float] = None,
    ) -> set[str]:
        """Return the set of tendency ids ``focal_id`` would see under these
        pull parameters. Useful for testing and for sizing queries."""
        radius = self.default_pull_radius if radius is None else radius
        min_weight = (
            self.default_pull_min_weight if min_weight is None else min_weight
        )
        return self._reachable(focal_id, radius, min_weight)

    def _reachable(
        self,
        origin_id: str,
        radius: int,
        min_weight: float,
    ) -> set[str]:
        """BFS from origin_id up to ``radius`` hops along edges >= ``min_weight``."""
        if not self.graph.has(origin_id):
            return {origin_id}

        seen: set[str] = {origin_id}
        frontier: list[str] = [origin_id]
        for _hop in range(radius):
            next_frontier: list[str] = []
            for node in frontier:
                for neighbor, _w in self.graph.neighbors(node, min_weight):
                    if neighbor not in seen:
                        seen.add(neighbor)
                        next_frontier.append(neighbor)
            if not next_frontier:
                break
            frontier = next_frontier
        return seen

    # ------------------------------------------------------------------
    # Convenience
    # ------------------------------------------------------------------

    def lineage_of(self, tendency_id: str) -> Optional[Lineage]:
        return self.lineages.get(tendency_id)

    def global_event_view(self) -> list[Event]:
        """Total ordering across all outboxes by engine_time.

        Each event lives in exactly one outbox (the origin's), so no
        deduplication is needed. Useful for inspection and tests.
        """
        out: list[Event] = []
        for ln in self.lineages.values():
            out.extend(ln.events())
        out.sort(key=lambda e: e.engine_time)
        return out


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def attach_lineage_to_tendencies(
    tendencies: Iterable,
    recorder: LineageRecorder,
) -> None:
    """Ensure every tendency has a lineage slot. Tendency must have ``id``."""
    for t in tendencies:
        recorder.register(t.id)
