"""
Lineage: per-tendency record of engine activity, scoped by propagation.

Events are not generated by an external clock. They *are* the engine's
activity: stakes placed, allocations shifted, tendencies born or
culled, claims mutated. The engine's tick is its own breath.

Each event has an originating tendency and an engine-time stamp from a
global monotonic counter. Engine-time is global (one clock for the
whole system) but does not map onto wall-clock or 4th-dimension time;
it only ticks when the engine acts.

A tendency's lineage is *its own activity* plus *the activity of
tendencies inside its stake-weight propagation radius*. Distant
tendencies -- those with edge weights trending to zero -- are simply
not visible. The graph topology is the visibility rule.

This means lineage scales naturally with sparsity. Sparse, coherent
equilibria produce compact per-tendency lineage; dense, incoherent
equilibria produce broader lineage. Same property that buys localized
inference buys bounded lineage.

There is no global event log. Per-tendency rings are authoritative.
Global views are reconstructed by unioning rings and deduplicating by
engine-time stamp.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Iterable, Optional


# ---------------------------------------------------------------------------
# Event types
# ---------------------------------------------------------------------------


class EventType(Enum):
    """The kinds of activity the engine emits."""

    STAKED              = "staked"               # tendency placed a stake
    ALLOCATION_SHIFTED  = "allocation_shifted"   # allocation changed by N
    BORN                = "born"                 # tendency was instantiated
    CULLED              = "culled"               # tendency was removed
    CLAIM_MUTATED       = "claim_mutated"        # tendency's claim refined


@dataclass(frozen=True)
class Event:
    """A single unit of engine activity.

    Parameters
    ----------
    engine_time:
        Monotonic counter value at the moment of emission. Globally
        unique within a clock; total order across all events.
    type:
        The kind of activity.
    origin_id:
        Id of the tendency whose activity caused this event. (For
        BORN/CULLED, this is the tendency being born/culled.)
    payload:
        Type-specific data (delta values, observation ids, claim text,
        co-participant ids, etc.). Keys are stable across event types
        of the same kind.
    wall_clock:
        Optional debug breadcrumb. Not authoritative.
    """

    engine_time: int
    type: EventType
    origin_id: str
    payload: dict = field(default_factory=dict)
    wall_clock: Optional[float] = None

    def to_dict(self) -> dict:
        return {
            "engine_time": self.engine_time,
            "type": self.type.value,
            "origin_id": self.origin_id,
            "payload": dict(self.payload),
            "wall_clock": self.wall_clock,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Event":
        return cls(
            engine_time=int(data["engine_time"]),
            type=EventType(data["type"]),
            origin_id=str(data["origin_id"]),
            payload=dict(data.get("payload", {})),
            wall_clock=data.get("wall_clock"),
        )


# ---------------------------------------------------------------------------
# Engine clock
# ---------------------------------------------------------------------------


@dataclass
class EngineClock:
    """Monotonic counter advanced once per event emission.

    Engine-time is global (one clock per arena/system) but is not
    mapped onto linear time. Branches in engine-time happen when
    parallel reseeds advance their own clocks independently; in that
    case each clone gets its own EngineClock instance.
    """

    value: int = 0

    def tick(self) -> int:
        """Advance and return the new value."""
        self.value += 1
        return self.value

    def now(self) -> int:
        """Current value without advancing."""
        return self.value


# ---------------------------------------------------------------------------
# Per-tendency lineage storage
# ---------------------------------------------------------------------------


@dataclass
class Lineage:
    """Per-tendency lineage: rolling allocation window + bounded event ring.

    Rolling allocation window (LOD 1 fodder): last N allocation values
    captured after each ALLOCATION_SHIFTED event for this tendency.

    Bounded event ring (LOD 2 fodder): last M events that propagated to
    this tendency. Older events fall off the back of the ring; if the
    full LOD-3 record is needed, it must be reconstructed by replaying
    available events against present state, or pulled from a separate
    high-LOD store.
    """

    allocation_window_capacity: int = 32
    event_ring_capacity: int = 256

    allocation_window: deque[float] = field(default_factory=lambda: deque(maxlen=32))
    event_ring: deque[Event] = field(default_factory=lambda: deque(maxlen=256))

    def __post_init__(self) -> None:
        # Re-bind deques to the configured capacities (the field defaults
        # always use 32/256 since dataclass defaults are evaluated once).
        if self.allocation_window.maxlen != self.allocation_window_capacity:
            self.allocation_window = deque(
                self.allocation_window, maxlen=self.allocation_window_capacity
            )
        if self.event_ring.maxlen != self.event_ring_capacity:
            self.event_ring = deque(
                self.event_ring, maxlen=self.event_ring_capacity
            )

    # ------------------------------------------------------------------
    # Append
    # ------------------------------------------------------------------

    def record_event(self, event: Event) -> None:
        """Append an event to the ring (oldest evicted on overflow)."""
        self.event_ring.append(event)

    def record_allocation(self, allocation: float) -> None:
        """Append a post-shift allocation value to the rolling window."""
        self.allocation_window.append(allocation)

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    def recent_allocations(self) -> list[float]:
        return list(self.allocation_window)

    def events(self) -> list[Event]:
        return list(self.event_ring)

    def latest_event(self) -> Optional[Event]:
        return self.event_ring[-1] if self.event_ring else None

    def events_of_type(self, type: EventType) -> list[Event]:
        return [e for e in self.event_ring if e.type == type]

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    def to_dict(self) -> dict:
        return {
            "allocation_window_capacity": self.allocation_window_capacity,
            "event_ring_capacity": self.event_ring_capacity,
            "allocation_window": list(self.allocation_window),
            "event_ring": [e.to_dict() for e in self.event_ring],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Lineage":
        ln = cls(
            allocation_window_capacity=int(data.get("allocation_window_capacity", 32)),
            event_ring_capacity=int(data.get("event_ring_capacity", 256)),
        )
        for v in data.get("allocation_window", []):
            ln.record_allocation(float(v))
        for ev in data.get("event_ring", []):
            ln.record_event(Event.from_dict(ev))
        return ln


# ---------------------------------------------------------------------------
# Stake-weight graph view (read-only structural input for propagation)
# ---------------------------------------------------------------------------


@dataclass
class StakeWeightGraph:
    """Symmetric stake-weight graph between tendencies.

    Edge weight between A and B is, by convention, the total absolute
    stake weight that A and B have placed on shared trees/observations.
    Higher weight => closer in the propagation neighborhood.

    This is a thin read-only view -- the recorder consults it but does
    not mutate it. The arena (or whatever produces equilibria) is
    responsible for keeping the graph current.
    """

    # weights[a][b] = weights[b][a] = positive float
    weights: dict[str, dict[str, float]] = field(default_factory=dict)

    def neighbors(self, tid: str, min_weight: float) -> list[tuple[str, float]]:
        """Tendencies connected to ``tid`` with edge weight >= ``min_weight``.

        Returns (neighbor_id, weight) sorted by weight descending. Excludes ``tid`` itself.
        """
        adj = self.weights.get(tid, {})
        out = [(o, w) for o, w in adj.items() if o != tid and w >= min_weight]
        out.sort(key=lambda pair: -pair[1])
        return out

    def has(self, tid: str) -> bool:
        return tid in self.weights

    def add_edge(self, a: str, b: str, weight: float) -> None:
        """Set the (symmetric) edge weight between a and b. Overwrites."""
        if a == b:
            return
        self.weights.setdefault(a, {})[b] = weight
        self.weights.setdefault(b, {})[a] = weight

    def add_tendency(self, tid: str) -> None:
        """Ensure a tendency exists in the graph (with no edges yet)."""
        self.weights.setdefault(tid, {})

    def remove_tendency(self, tid: str) -> None:
        """Remove a tendency and all its edges from the graph."""
        for other in list(self.weights.get(tid, {})):
            self.weights[other].pop(tid, None)
        self.weights.pop(tid, None)

    def edge_weight(self, a: str, b: str) -> float:
        return self.weights.get(a, {}).get(b, 0.0)


# ---------------------------------------------------------------------------
# Lineage recorder
# ---------------------------------------------------------------------------


@dataclass
class LineageRecorder:
    """Walks the stake-weight graph to deliver events to per-tendency lineage.

    Construction:

        recorder = LineageRecorder(
            clock=EngineClock(),
            graph=stake_weight_graph,
            lineages={tid: Lineage() for tid in tendencies},
            propagation_min_weight=0.01,
            propagation_radius=2,
        )

    Emission:

        recorder.emit(EventType.STAKED, origin_id="alpha", payload={...})

    Propagation:
      - The originating tendency always records the event (radius 0).
      - For each step up to ``propagation_radius``, the recorder visits
        neighbors whose edge weight is >= ``propagation_min_weight``.
      - A tendency records the event at most once per emission.

    The recorder does not own the tendencies or the graph; it consults
    them through the structures passed in at construction.
    """

    clock: EngineClock
    graph: StakeWeightGraph
    lineages: dict[str, Lineage] = field(default_factory=dict)
    propagation_min_weight: float = 0.01
    propagation_radius: int = 2

    # ------------------------------------------------------------------
    # Setup helpers
    # ------------------------------------------------------------------

    def register(self, tendency_id: str, lineage: Optional[Lineage] = None) -> Lineage:
        """Add a lineage slot for a tendency. Idempotent."""
        if tendency_id in self.lineages:
            return self.lineages[tendency_id]
        ln = lineage or Lineage()
        self.lineages[tendency_id] = ln
        self.graph.add_tendency(tendency_id)
        return ln

    def unregister(self, tendency_id: str) -> Optional[Lineage]:
        """Remove a tendency's lineage slot. Returns the removed lineage."""
        self.graph.remove_tendency(tendency_id)
        return self.lineages.pop(tendency_id, None)

    # ------------------------------------------------------------------
    # Emission
    # ------------------------------------------------------------------

    def emit(
        self,
        type: EventType,
        origin_id: str,
        payload: Optional[dict] = None,
        wall_clock: Optional[float] = None,
    ) -> Event:
        """Build an event, propagate it, and return it.

        The event is recorded on the origin and on every tendency
        reachable within ``propagation_radius`` hops along edges of
        weight >= ``propagation_min_weight``. Each tendency records the
        event at most once.
        """
        event = Event(
            engine_time=self.clock.tick(),
            type=type,
            origin_id=origin_id,
            payload=dict(payload or {}),
            wall_clock=wall_clock,
        )
        for reached in self._reachable(origin_id):
            ln = self.lineages.get(reached)
            if ln is not None:
                ln.record_event(event)
        return event

    def emit_allocation_shift(
        self,
        origin_id: str,
        new_allocation: float,
        delta: float,
        wall_clock: Optional[float] = None,
    ) -> Event:
        """Convenience: emit an ALLOCATION_SHIFTED event and update the
        origin tendency's rolling allocation window."""
        event = self.emit(
            type=EventType.ALLOCATION_SHIFTED,
            origin_id=origin_id,
            payload={"new_allocation": new_allocation, "delta": delta},
            wall_clock=wall_clock,
        )
        ln = self.lineages.get(origin_id)
        if ln is not None:
            ln.record_allocation(new_allocation)
        return event

    # ------------------------------------------------------------------
    # Propagation
    # ------------------------------------------------------------------

    def _reachable(self, origin_id: str) -> set[str]:
        """BFS up to ``propagation_radius`` hops, edges >= min_weight."""
        if not self.graph.has(origin_id):
            # Origin not in graph; only it records (if it has a lineage slot).
            return {origin_id}

        seen: set[str] = {origin_id}
        frontier: list[str] = [origin_id]
        for _hop in range(self.propagation_radius):
            next_frontier: list[str] = []
            for node in frontier:
                for neighbor, _w in self.graph.neighbors(
                    node, self.propagation_min_weight
                ):
                    if neighbor not in seen:
                        seen.add(neighbor)
                        next_frontier.append(neighbor)
            if not next_frontier:
                break
            frontier = next_frontier
        return seen

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    def lineage_of(self, tendency_id: str) -> Optional[Lineage]:
        return self.lineages.get(tendency_id)

    def global_event_view(self) -> list[Event]:
        """Reconstruct a global event ordering by deduplicating across lineages.

        This is *reconstructed*, not stored. Most queries should be
        local; this exists for inspection.
        """
        seen: dict[int, Event] = {}
        for ln in self.lineages.values():
            for ev in ln.event_ring:
                seen.setdefault(ev.engine_time, ev)
        return [seen[k] for k in sorted(seen)]


# ---------------------------------------------------------------------------
# Helpers for use from tests / arena
# ---------------------------------------------------------------------------


def attach_lineage_to_tendencies(
    tendencies: Iterable,
    recorder: LineageRecorder,
) -> None:
    """Ensure every tendency in ``tendencies`` has a lineage slot in the recorder.

    Tendencies are duck-typed: anything with an ``id`` attribute works.
    Use this when bootstrapping a TendencySet against a fresh recorder.
    """
    for t in tendencies:
        recorder.register(t.id)
