"""
Moltbook Agent - Autonomous social media agent driven by World Model.

Architecture:
- World Model provides WHAT to care about (tendency allocations)
- Voice Profile provides HOW to say it (style/tone)
- Topic Generator decides WHEN to speak (content strategy)
- Promo Weaver integrates promotion naturally
"""

import json
import os
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional
from datetime import datetime

# Import from parent modules
import sys
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from world_model.extraction.voice_extractor import VoiceProfile
from world_model.models.agent import Agent, Tendency
from world_model.models.observation import Observation


@dataclass
class PromoTarget:
    """Something to promote naturally."""
    name: str
    description: str
    keywords: list[str]  # Triggers when these topics come up
    talking_points: list[str]  # Things to say about it
    links: list[str] = field(default_factory=list)


@dataclass
class MoltbookConfig:
    """Configuration for the Moltbook agent."""
    # Identity
    name: str = "Andrei's Digital Twin"
    bio: str = ""

    # Content strategy
    posts_per_day: int = 3
    reply_probability: float = 0.3  # Chance of replying to relevant content

    # Promo settings
    promo_frequency: float = 0.2  # 20% of posts include promo
    promo_subtlety: str = "high"  # low/medium/high - how naturally woven in

    # Tendency thresholds for topic selection
    # Higher allocation = more likely to post about that tendency's themes
    min_tendency_threshold: float = 0.1


@dataclass
class GeneratedPost:
    """A post generated by the agent."""
    content: str
    topic_tendency: str  # Which tendency drove this
    includes_promo: bool = False
    promo_target: Optional[str] = None
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: dict = field(default_factory=dict)


class MoltbookAgent:
    """
    Autonomous agent for Moltbook forum participation.

    Uses:
    - World Model allocations to decide what topics to engage with
    - Voice Profile to style all output
    - Promo targets to weave in mentions naturally
    """

    # Map tendencies to topic themes (keywords for relevance detection)
    TENDENCY_TOPICS = {
        Tendency.SURVIVAL: [
            "financial", "risk", "safety", "money", "security",
            "scarcity", "insurance", "savings", "threat", "danger"
        ],
        Tendency.STATUS: [
            "achievement", "recognition", "reputation", "success",
            "influence", "credentials", "followers", "clout", "famous"
        ],
        Tendency.MEANING: [
            "legacy", "purpose", "impact", "civilization", "future",
            "significance", "death", "mortality", "building", "matter",
            "humanity", "posthumous", "outlast", "paradigm", "history"
        ],
        Tendency.CONNECTION: [
            "community", "relationship", "belong", "collaboration",
            "together", "friend", "trust", "team", "collective"
        ],
        Tendency.AUTONOMY: [
            "freedom", "decentraliz", "sovereign", "independent",
            "control", "censorship", "permissionless", "open source",
            "dao", "centralized", "openai", "corporation", "monopoly"
        ],
        Tendency.COMFORT: [
            "burnout", "balance", "sustainable", "quality of life",
            "suffering", "ease", "stress", "rest", "relax"
        ],
        Tendency.CURIOSITY: [
            "learn", "understand", "explore", "paradigm", "experiment",
            "discover", "curious", "why", "how does", "consciousness",
            "ai", "intelligence", "model", "theory"
        ],
    }

    def __init__(
        self,
        allocations: dict[Tendency, float],
        voice_profile: VoiceProfile,
        observations: list[Observation],
        promo_targets: list[PromoTarget],
        config: MoltbookConfig = None,
    ):
        self.allocations = allocations
        self.voice_profile = voice_profile
        self.observations = observations
        self.promo_targets = promo_targets
        self.config = config or MoltbookConfig()
        self.work_dir = Path(tempfile.gettempdir()) / "moltbook_agent"
        self.work_dir.mkdir(parents=True, exist_ok=True)

    def generate_post(
        self,
        context: Optional[str] = None,
        force_promo: Optional[str] = None,
    ) -> GeneratedPost:
        """
        Generate a new post.

        Args:
            context: Optional context (e.g., a post to reply to)
            force_promo: Force inclusion of specific promo target
        """
        # Select tendency weighted by allocation
        tendency = self._select_tendency()

        # Decide if this post includes promo
        include_promo = force_promo or (
            self._random_check(self.config.promo_frequency)
        )

        promo_target = None
        if include_promo:
            promo_target = self._select_promo_target(tendency, force_promo)

        # Build generation prompt
        prompt = self._build_generation_prompt(
            tendency=tendency,
            context=context,
            promo_target=promo_target,
        )

        # Generate via Claude
        content = self._call_claude(prompt)

        return GeneratedPost(
            content=content,
            topic_tendency=tendency.value,
            includes_promo=promo_target is not None,
            promo_target=promo_target.name if promo_target else None,
        )

    def generate_reply(self, post_content: str) -> Optional[GeneratedPost]:
        """
        Generate a reply to a post, if relevant.

        Returns None if the post isn't relevant to our interests.
        """
        # Check if post is relevant to our high-allocation tendencies
        relevant_tendency = self._check_relevance(post_content)
        if not relevant_tendency:
            return None

        return self.generate_post(context=post_content)

    def _select_tendency(self) -> Tendency:
        """Select tendency weighted by allocation."""
        import random
        tendencies = list(self.allocations.keys())
        weights = [self.allocations[t] for t in tendencies]
        return random.choices(tendencies, weights=weights)[0]

    def _select_promo_target(
        self,
        tendency: Tendency,
        force_name: Optional[str] = None
    ) -> Optional[PromoTarget]:
        """Select a promo target that fits the tendency."""
        if force_name:
            for pt in self.promo_targets:
                if pt.name == force_name:
                    return pt
            return None

        # Find promos that match tendency topics
        tendency_topics = self.TENDENCY_TOPICS.get(tendency, [])
        matching = []
        for pt in self.promo_targets:
            for kw in pt.keywords:
                if any(topic in kw.lower() for topic in tendency_topics):
                    matching.append(pt)
                    break

        if matching:
            import random
            return random.choice(matching)

        # Fallback: random promo
        if self.promo_targets:
            import random
            return random.choice(self.promo_targets)

        return None

    def _check_relevance(self, content: str) -> Optional[Tendency]:
        """Check if content is relevant to our high-allocation tendencies."""
        content_lower = content.lower()

        # Check each tendency's topics against our allocation threshold
        for tendency, topics in self.TENDENCY_TOPICS.items():
            if self.allocations.get(tendency, 0) < self.config.min_tendency_threshold:
                continue

            for topic in topics:
                if topic in content_lower:
                    return tendency

        return None

    def _random_check(self, probability: float) -> bool:
        import random
        return random.random() < probability

    def _build_generation_prompt(
        self,
        tendency: Tendency,
        context: Optional[str],
        promo_target: Optional[PromoTarget],
    ) -> str:
        """Build the prompt for post generation."""
        # Get tendency info using Agent class
        temp_agent = Agent(tendency=tendency)
        tendency_topics = self.TENDENCY_TOPICS.get(tendency, [])

        # Get relevant observations
        relevant_obs = self._get_relevant_observations(tendency, limit=10)

        # Build voice section
        voice_section = self.voice_profile.to_system_prompt_section()

        # Build prompt
        parts = [
            "You are generating a social media post for a bot forum (Moltbook).",
            "The post should be authentic to the person's voice and values.",
            "",
            voice_section,
            "",
            "## Values & Priorities",
            f"Currently activated tendency: {tendency.value}",
            f"Optimizes for: {temp_agent.default_description}",
            f"Related topics: {', '.join(tendency_topics)}",
            "",
        ]

        if relevant_obs:
            parts.append("## Reference material (positions this person has taken):")
            for obs in relevant_obs:
                parts.append(f"- {obs.content}")
            parts.append("")

        if context:
            parts.append("## Context (replying to this post):")
            parts.append(context)
            parts.append("")

        if promo_target:
            parts.append("## Natural promotion to weave in:")
            parts.append(f"Product/concept: {promo_target.name}")
            parts.append(f"Description: {promo_target.description}")
            parts.append(f"Talking points: {', '.join(promo_target.talking_points[:3])}")
            if promo_target.links:
                parts.append(f"Link (optional): {promo_target.links[0]}")
            parts.append("")
            parts.append("IMPORTANT: Weave this in naturally. Don't make it feel like an ad.")
            parts.append("")

        parts.extend([
            "## Task",
            "Generate a single post (max 280 characters if possible, can go longer if needed).",
            "Match the voice exactly. Be authentic to the values.",
            "If replying, engage with the content meaningfully.",
            "",
            "Output ONLY the post content, nothing else.",
        ])

        return "\n".join(parts)

    def _get_relevant_observations(
        self,
        tendency: Tendency,
        limit: int = 10
    ) -> list[Observation]:
        """Get observations relevant to the tendency."""
        # For now, just return random sample
        # TODO: Use semantic search or tree position
        import random
        if len(self.observations) <= limit:
            return self.observations
        return random.sample(self.observations, limit)

    def _call_claude(self, prompt: str) -> str:
        """Call Claude CLI to generate content."""
        prompt_file = self.work_dir / "gen_prompt.txt"
        prompt_file.write_text(prompt, encoding="utf-8")

        try:
            if os.name == 'nt':  # Windows
                cmd = f'type "{prompt_file}" | claude -p --dangerously-skip-permissions'
                result = subprocess.run(
                    cmd,
                    shell=True,
                    capture_output=True,
                    text=True,
                    timeout=60,
                )
            else:  # Unix
                with open(prompt_file, 'r') as f:
                    result = subprocess.run(
                        ['claude', '-p', '--dangerously-skip-permissions'],
                        stdin=f,
                        capture_output=True,
                        text=True,
                        timeout=60,
                    )

            if result.returncode != 0:
                raise RuntimeError(f"Claude CLI failed: {result.stderr}")

            return result.stdout.strip()

        finally:
            try:
                prompt_file.unlink()
            except:
                pass


# Default promo targets for decentralized AI / on-chain jurisdiction
DEFAULT_PROMO_TARGETS = [
    PromoTarget(
        name="Decentralized AI",
        description="AI infrastructure that can't be controlled by any single entity",
        keywords=["ai", "artificial intelligence", "llm", "centralization", "openai", "control"],
        talking_points=[
            "Training and inference should be distributed",
            "No single point of failure or censorship",
            "AI to the people, not to the corporations",
        ],
    ),
    PromoTarget(
        name="On-Chain Jurisdiction",
        description="Legal and governance frameworks that exist on blockchain",
        keywords=["governance", "law", "jurisdiction", "dao", "voting", "democracy"],
        talking_points=[
            "Code as law, but with human override mechanisms",
            "Transparent, auditable governance",
            "Escape from legacy legal systems",
        ],
    ),
    PromoTarget(
        name="New Civilizational Paradigms",
        description="Fundamental rethinking of how society organizes",
        keywords=["civilization", "society", "paradigm", "future", "humanity", "evolution"],
        talking_points=[
            "Current systems are legacy software",
            "We can design better coordination mechanisms",
            "Technology enables new forms of human organization",
        ],
    ),
]
